model_list:
  - model_name: "claude-sonnet-4-6"
    litellm_params:
      model: github_copilot/gpt-4.1

  - model_name: "claude-opus-4-6"
    litellm_params:
      model: github_copilot/gpt-5.3-codex

  - model_name: "claude-haiku-4-5-20251001"
    litellm_params:
      model: github_copilot/gpt-5-mini

general_settings:
  master_key: "sk-litellm-1234"
